### ISSUE TITLE
Porting the library to laravel

### ISSUE THREAD

**Issue by Kaabi** [scoumbourdis/grocery-crud#292]
is there any chance soon to see grocerycrud library ported for laravel ? everyone know that codeigniter update progress not going anywhere further than just some lack of bugs fixs once or twice a year till is abandon by developers, because someone like me seeking for up to date framework and the only thing currently giving power to ci is grocery-crud nothing else worth it in CI.

**Comment by iridion9** [comment]
I hope GroceryCRUD will not leave CodeIgniter. 4.0 is coming soon.
When are you going to release GroceryCRUD that support CodeIgniter 3.0?

Thanks in advance.

**Comment by iridion9** [comment]
I tried Laravel it is too often updated. and there i a negative side with update often.
CodeIgniter is slow but very stable.

**Comment by bvrignaud** [comment]
I don't understand your question, CroceryCRUD is already OK for CI 3 !
I use it everiday.

**Comment by airways** [comment]
My thought would be that it'd be best to try to make GroceryCRUD as a framework agnostic but PSR compliant library. There should not really be any need to have tight integration with a particular library (although that can be provided as add on bundles for each framework as needed), it would be great if you could use GroceryCRUD by itself for instance, with a micro framework such as Silex.

Anything a framework could provide can be easily supplied by a small PSR compliant library (database access, forms, etc.). I really think this would be a better route for the project than requiring Laravel since not everyone uses it, although it is

**Comment by andyhough** [comment]
Airways,  Thank you for your concept.  I agree. I think that Johnny has done a beautiful thing creating Grocery Crud. I have looked far and wide for any CRUD framework that is as attractive or functional, and there are none that have OOTB capabilities like GC. Having said that, it seems Johnny is letting his work get in the way of his extra curricular time in updating and supporting GC.  So maybe he needs some help.  

I am wondering if we could put together a virtual project team of skilled collaborators to help Johnny take GC to the next level, which is exactly what you just described.  

The way I would start is by having a few conference calls with Johnny to understand the work that was necessary to port Image Crud to Laravel, and use that as a baseline inventory of framework touch points.  Then we can use that to identify all the functionality that a framework needs to provide, and parse out the work. 

The forum here is still fairly robust, so I think there is some interest, and it is probably important to at minimum help Johnny hang his star on Laravel since the talk on the street is that CI is beginning to fade out of the top 10 frameworks as others begin to attract large followings. 

First step is to have a chat with Johnny to see where he is at, and see if he is willing and able to let us help him take this to a new level.  

Thoughts?
