### ISSUE TITLE
WebSite Down

### ISSUE THREAD

**Issue by r1800** [scoumbourdis/grocery-crud#423]
Hi,

Just to let you know that grocerycrud website is down. 

Date: 29-Aug-2017 13:00 GMT+1.

Chers
R

**Comment by scoumbourdis** [comment]
Already report it on twitter: https://twitter.com/groceryCRUD/status/902452245530333184 but unfortunately it is 3 hours down although the hosting provider told me that it will be only for 30 minutes max.

I guess this is the right time to change hosting. By the way I am using: https://www.jolt.co.uk/ 

I will update this ticket and close it once it is up and running again. We are really sorry for that. I will take serious decisions after that.

Regards
Johnny

**Comment by r1800** [comment]
Thank you for the update. Unfortunately I haven’t checked the tweeter account. Apologies for making you lose your precious time dealing with my ticket.

If you aren’t happy with jolt have a got with OVH. We currently use it and never had any major issues (disclaimer: I don’t know anyone or am related in anyway with OVH apart from being a paying customer – we use their services as our VPS provider and part of our hosting infrastructure).

**Comment by scoumbourdis** [comment]
Hello @r1800 and thank you for your suggestion.

Actually the thing with my hosting provider is that it was initially called https://www.webhostingbuzz.com/ and they had the https://www.webhostingbuzz.com/ (still exist) and https://www.webhostingbuzz.co.uk/ and it was just AMAZING. It was the greatest product ever! Great service and 100% uptime. At the future this was renamed to jolt and probably other companies was bought in order to support the UK region and everything was start breaking. The customer support didn't reply on time, random bugs was coming up... e.t.c.

What I am trying to say is that even if you are happy with the service of OVH we really don't know the future of the service and we can't really know. I am going to try AWS but if I find it more expensive than expected I will go back and check OVH ;-)

Can I ask you how many visits are you getting per day? Grocery CRUD is getting roughly 2000 visits per day. I know that this is not very high traffic but it needs to be always 100% up as there is not any excuse to not have a documentation up and running guaranteed.

Thanks in advance for the help
Johnny

**Comment by r1800** [comment]
Hi,

To be honest we use our VPSs (3 in total) mainly for intranet. We have about 50 users but VM’s are running CPU/memory intensive web apps for intranets/back-office

We do have a few wordpress instances on the WAN but to be honest I don’t monitor it very often as they seem to keep running OK but I doubt very much that we are having more than 100 concurrent connections.

I’ve had a look at AWS but was a bit frightened that costs would spiral out of control so I’ve decided with OVH (fixed cost SSD VPS).

Ricardo

**Comment by scoumbourdis** [comment]
After our biggest downtime in history: 4.5h we are now up and running! Thank you also @r1800 for providing me the details. I will have it a second thought and I will let you know.

Happily closing this ticket.

**Comment by blakdronzer** [comment]
It still says me the same stuff

www.grocerycrud.com Driver Error
There appears to be an error with the database.
If you are seeing this page, it means there was a problem communicating with our database. Sometimes this error is temporary and will go away when you refresh the page. Sometimes the error will need to be fixed by an administrator before the site will become accessible again. 

You can try to refresh the page by clicking here


Also - What i experienced 1 thing brother was the SSL Certificate was expired. Think it needs to be renewed too.

**Comment by scoumbourdis** [comment]
Hello @blakdronzer ,

Yes I woke up today and instead of having my normal schedule I was speaking with the hosting provider to fix all that stuff. Those are fixed now.

Please let me know if you are still having issues so I will investigate more.

Thanks
Johnny

**Comment by r1800** [comment]
Hello,

Bad news I’m afraid:

URL: https://www.grocerycrud.com/forums/tags/forums/dropdown/

www.grocerycrud.com Driver Error
There appears to be an error with the database.
If you are seeing this page, it means there was a problem communicating with our database. Sometimes this error is temporary and will go away when you refresh the page. Sometimes the error will need to be fixed by an administrator before the site will become accessible again.

You can try to refresh the page by clicking here<https://www.grocerycrud.com/forums/tags/forums/dropdown/>
← Return to the index<https://www.grocerycrud.com/index.php>

**Comment by scoumbourdis** [comment]
:sob: ok. I will have it a look tonight. Re-opening the ticket.

**Comment by scoumbourdis** [comment]
Hello @r1800 ,

This is now fixed as well. Please let me know if you find any other page with an error.

Till then I am crossing fingers :crossed_fingers: 

Regards
Johnny

**Comment by blakdronzer** [comment]
hahaha - true brother - i could finally log in.. and was perfect timing.. i was about to click on the link and i saw your message - it just started back :) 👍

**Comment by scoumbourdis** [comment]
Again sorry for that guys. I am just only one person after all 😄 

Really appreciate your patient and I hope you will enjoy Grocery CRUD with no issues from now on ;-)

Happy GCing

**Comment by blakdronzer** [comment]
yes.. i can say 4 myself.. and i do understand .. 
and well.. i am happy that u gelled with my Happy GCing :)
Happy GCing 2 u too 👍
